{
  "hash": "cb8e9bd37b16d371058d0a0a5f56a70d",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"SME Strategic Financial Diagnostic\"\ndescription: \"A professional audit-grade financial analysis tool utilizing Python to evaluate profitability trajectories and liquidity health for Irish SMEs.\"\nauthor: \"SONGTING CHEN\"\ndate: \"2025-04-15\"\ncategories: [\"Financial Audit\", \"SME Strategy\", \"Python\"]\njupyter: python3\n\nformat:\n  html:\n   \n    page-layout: article\n    max-width: 900px           \n    toc: true\n    toc-location: right        \n    toc-title: \"Audit Sections\"\n    \n    code-fold: true\n    code-summary: \"View Code (Python)\"\n    \n    \n    theme: flatly               \n    highlight-style: arrow      \n    \n    \n    css: |\n      /* Page background */\n      body {\n        background-color: #ffffff;\n        color: #2c3e50;\n        font-family: 'Georgia', serif; \n      }\n      \n      /* Title block style */\n      .quarto-title {\n        border-left: 10px solid #003366; \n        padding-left: 20px;\n        margin-top: 4rem;\n        background-color: #f8f8fa;\n        padding-top: 30px;\n        padding-bottom: 30px;\n      }\n      \n      /* Chart centering */\n      .cell-output-display {\n        display: flex;\n        justify-content: center;\n        margin: 50px 0;\n        padding: 20px;\n        background: #fff;\n        border: 1px solid #eee; \n        box-shadow: 5px 5px 15px rgba(0,0,0,0.02);\n      }\n      \n      /* Table output style */\n      .cell-output-stdout pre {\n        margin: 30px auto;\n        display: table;\n        border-top: 3px solid #C5A059; \n        border-bottom: 3px solid #C5A059;\n        padding: 20px 40px;\n        background-color: #fff;\n        font-family: 'Courier New', monospace;\n      }\n      \n      /* Section header */\n      h2 {\n        color: #003366;\n        text-transform: uppercase; \n        letter-spacing: 1px;\n        font-size: 1.4rem;\n        border-bottom: 1px solid #C5A059; \n        padding-bottom: 5px;\n      }\n---\n\n## 1. Executive Environment Setup\n\n::: {#09dca633 .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport plotly.graph_objects as go\nfrom plotly.subplots import make_subplots\n\n\nNAVY = \"#003366\"\nGOLD = \"#C5A059\"\nGREY = \"#F2F2F2\"\nDARK_GREY = \"#404040\"\n\n\nplt.style.use('seaborn-v0_8-white')\nplt.rcParams.update({\n    'font.family': 'sans-serif',\n    'font.sans-serif': ['Arial'],\n    'axes.edgecolor': DARK_GREY,\n    'axes.labelcolor': DARK_GREY,\n    'xtick.color': DARK_GREY,\n    'ytick.color': DARK_GREY\n})\n```\n:::\n\n\n---\n\n\n## 2. Core Financial Datasets (2022–2025)\n\n::: {#de16c1f2 .cell execution_count=2}\n``` {.python .cell-code}\n#data\nimport pandas as pd\n\n# --- 1. Dataset Initialization ---\n# Defining historical and projected financial data for analysis\nfinancial_data = {\n    'Year': [2022, 2023, 2024, 2025],\n    'Revenue': [185000, 210000, 235000, 268000],\n    'COGS': [95000, 108000, 119000, 132000],\n    'Op_Expenses': [61500, 67800, 74500, 86200],\n    'Net_Profit': [28500, 34200, 41500, 49800],\n    'Current_Assets': [46000, 52000, 59000, 67000],\n    'Current_Liabilities': [22000, 24000, 26000, 29000]\n}\n\ndf = pd.DataFrame(financial_data)\n\n# --- 2. Financial Calculation Logic ---\n# Deriving key profitability and liquidity metrics \ndf['Gross_Profit'] = df['Revenue'] - df['COGS']\ndf['GPM'] = (df['Gross_Profit'] / df['Revenue']) * 100\ndf['NPM'] = (df['Net_Profit'] / df['Revenue']) * 100\ndf['Current_Ratio'] = df['Current_Assets'] / df['Current_Liabilities']\n\n# --- 3. Strategic KPI Summary Report ---\n# Formatting the output table to align with professional accounting standards\nstyled_df = df[['Year', 'GPM', 'NPM', 'Current_Ratio']].copy()\nstyled_df.columns = ['Fiscal Year', 'Gross Margin (%)', 'Net Margin (%)', 'Liquidity (Ratio)']\n\n# Print formatted summary for the ePortfolio display\nprint(\"\\n\" + \"=\" * 70)\nprint(f\"{'STRATEGIC KPI SUMMARY':^70}\")\nprint(\"=\" * 70)\nprint(styled_df.to_string(index=False, float_format=lambda x: f'{x:.2f}'))\nprint(\"=\" * 70)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n======================================================================\n                        STRATEGIC KPI SUMMARY                         \n======================================================================\n Fiscal Year  Gross Margin (%)  Net Margin (%)  Liquidity (Ratio)\n        2022             48.65           15.41               2.09\n        2023             48.57           16.29               2.17\n        2024             49.36           17.66               2.27\n        2025             50.75           18.58               2.31\n======================================================================\n```\n:::\n:::\n\n\n---\n\n## 3. Profitability Engine: Dual-Axis Trend Analysis\n\n::: {#d97d5297 .cell fig-height='4' fig-width='6.5' execution_count=3}\n``` {.python .cell-code}\n# Reduce figsize to (7, 4.5) for a more compact output\nfig, ax1 = plt.subplots(figsize=(7, 4.5))\n\n# Plot Revenue bars (using defined NAVY color)\nbars = ax1.bar(df['Year'], df['Revenue'], color=NAVY, alpha=0.85, label='Total Revenue', width=0.4)\nax1.set_ylabel('Revenue (EUR)', fontweight='bold', color=NAVY, fontsize=9)\nax1.tick_params(axis='y', labelcolor=NAVY, labelsize=8)\n\n# Create secondary y-axis for profit margin\nax2 = ax1.twinx()\nax2.plot(df['Year'], df['NPM'], color=GOLD, marker='D', linewidth=2.5, markersize=6, label='Net Profit Margin (%)')\nax2.set_ylabel('Net Margin (%)', fontweight='bold', color=GOLD, fontsize=9)\nax2.tick_params(axis='y', labelcolor=GOLD, labelsize=8)\n\n# Aesthetic optimizations\nplt.title('Performance Scaling: Revenue vs. Profitability', fontsize=11, fontweight='bold', pad=20)\nax1.set_xticks(df['Year'])\nax1.tick_params(axis='x', labelsize=8)\nax1.grid(axis='y', linestyle='--', alpha=0.2)\n\n# Merge legends and adjust font size\nlines, labels = ax1.get_legend_handles_labels()\nlines2, labels2 = ax2.get_legend_handles_labels()\nax2.legend(lines + lines2, labels + labels2, loc='upper left', frameon=False, fontsize=8)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](project1_financial_analysis_files/figure-html/cell-4-output-1.png){width=665 height=422 fig-align='center'}\n:::\n:::\n\n\n- Strategic Insight: Net margins expanded to 18.6% alongside revenue growth, confirming strong economies of scale and optimized operational leverage.\n\n---\n\n## 4. Cost Structure Breakdown (Waterfall Analysis)\n\n::: {#85477777 .cell fig-height='4' fig-width='6' execution_count=4}\n``` {.python .cell-code}\nlatest = df.iloc[-1]\n\n# Construct Plotly waterfall object with optimized dimensions\nfig = go.Figure(go.Waterfall(\n    name = \"2025 Financials\", orientation = \"v\",\n    measure = [\"relative\", \"relative\", \"relative\", \"total\"],\n    x = [\"Revenue\", \"COGS\", \"Op Exp\", \"Net Profit\"], # Abbreviated labels\n    textposition = \"outside\",\n    text = [f\"+{latest['Revenue']}\", f\"-{latest['COGS']}\", f\"-{latest['Op_Expenses']}\", f\"{latest['Net_Profit']}\"],\n    y = [latest['Revenue'], -latest['COGS'], -latest['Op_Expenses'], latest['Net_Profit']],\n    connector = {\"line\":{\"color\":\"rgb(63, 63, 63)\"}},\n    increasing = {\"marker\":{\"color\": NAVY}},\n    decreasing = {\"marker\":{\"color\": GOLD}},\n    totals = {\"marker\":{\"color\": DARK_GREY}},\n    textfont=dict(size=10) # Reduce text size on bars\n))\n\nfig.update_layout(\n    title = dict(text=\"Profit Erosion Mapping (2025 FY)\", font=dict(size=13)),\n    showlegend = False,\n    plot_bgcolor = 'white',\n    width=550, height=380, # Compressed container size\n    margin=dict(t=60, b=40, l=40, r=40),\n    xaxis=dict(tickfont=dict(size=10)),\n    yaxis=dict(tickfont=dict(size=10))\n)\n\nfig.show()\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG\"></script><script>if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}</script>                <script>window.PlotlyConfig = {MathJaxConfig: 'local'};</script>\n        <script charset=\"utf-8\" src=\"https://cdn.plot.ly/plotly-3.5.0.min.js\" integrity=\"sha256-fHbNLP+GlIXN+efbQec78UkemUz3NJp7UmfGxC1tNxs=\" crossorigin=\"anonymous\"></script>                <div id=\"8aae716c-78f7-448c-9d1e-c8d402a788d1\" class=\"plotly-graph-div\" style=\"height:380px; width:550px;\"></div>            <script>                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById(\"8aae716c-78f7-448c-9d1e-c8d402a788d1\")) {                    Plotly.newPlot(                        \"8aae716c-78f7-448c-9d1e-c8d402a788d1\",                        [{\"connector\":{\"line\":{\"color\":\"rgb(63, 63, 63)\"}},\"decreasing\":{\"marker\":{\"color\":\"#C5A059\"}},\"increasing\":{\"marker\":{\"color\":\"#003366\"}},\"measure\":[\"relative\",\"relative\",\"relative\",\"total\"],\"name\":\"2025 Financials\",\"orientation\":\"v\",\"text\":[\"+268000.0\",\"-132000.0\",\"-86200.0\",\"49800.0\"],\"textfont\":{\"size\":10},\"textposition\":\"outside\",\"totals\":{\"marker\":{\"color\":\"#404040\"}},\"x\":[\"Revenue\",\"COGS\",\"Op Exp\",\"Net Profit\"],\"y\":[268000.0,-132000.0,-86200.0,49800.0],\"type\":\"waterfall\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermap\":[{\"type\":\"scattermap\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30}}},\"title\":{\"font\":{\"size\":13},\"text\":\"Profit Erosion Mapping (2025 FY)\"},\"margin\":{\"t\":60,\"b\":40,\"l\":40,\"r\":40},\"xaxis\":{\"tickfont\":{\"size\":10}},\"yaxis\":{\"tickfont\":{\"size\":10}},\"showlegend\":false,\"plot_bgcolor\":\"white\",\"width\":550,\"height\":380},                        {\"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('8aae716c-78f7-448c-9d1e-c8d402a788d1');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };            </script>        </div>\n```\n:::\n:::\n\n\n- Cost Diagnostic: While COGS remains the primary profit drain (49% of turnover), the firm maintains a healthy bottom-line conversion of €49,800.\n\n---\n\n## 5. Strategic Business Insights\n- Expansion Velocity: Revenue growth sustained a 12% CAGR, indicating robust market penetration in the Irish SME sector.\n- Operational Leverage: The widening gap between Gross and Net Margins suggests optimized operating cost structures as the business scales.\n- Liquidity Fortress: A Current Ratio of 2.31 (2025) provides a significant buffer for short-term liabilities, far exceeding the industry standard of 1.5.\n\n---\n\n## 6. Technical Expertise & Methodology\n- Quantitative Analytics: Advanced financial modeling using Pandas for structured data manipulation.\n- Dynamic Visualization: Integration of Matplotlib Dual-Axis and Plotly Waterfall charts for multi-dimensional performance tracking.\n- Accounting Theory: Applied Vertical and Horizontal Analysis techniques to evaluate income statement integrity.\n\n",
    "supporting": [
      "project1_financial_analysis_files\\figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n<script>\nwindow.PlotlyConfig = {MathJaxConfig: 'local'};\nif (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}\n</script>\n<script type=\"module\">import \"https://cdn.plot.ly/plotly-3.5.0.min\"</script>\n\n"
      ]
    }
  }
}